# Generated by Django 5.1 on 2024-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
